### ISSUE TITLE
Country codes in phone numbers

### ISSUE THREAD

**Issue by moonlight200** [machbarschaft/machbarschaft-android#24]
When users enters their phone number, they can use two different forms:
- `+49 123 456789`, or
- `0123 456789`

Both are correct representations of the number, but the users have to enter the same number in the same format when they login again. This can cause an issue with users not being able to login, without having done something wrong.

We should decide on one of the two representations and make sure that we stick with that. I think that the more reasonable representation includes the country codes, as that allows us to have users from different countries with otherwise identical phone numbers.

Therefore I propose two approaches:

## Approach A
We infer the country code. Even if the user doesn't explicitly enter the country code, we add a country code "behind the scenes". This requires a method that can reliably determine the country code that should be used with the users number. (Maybe it is possible to get the number from the SIM card or something)

## Approach B
We force the user to enter the country code. This could look similar to what WhatsApp does in its registration form:
<img src="https://www.researchgate.net/publication/326550093/figure/fig6/AS:651399683665921@1532317195559/WhatsApp-registration-process.png" width="200px" />

**Comment by Basler182** [comment]
Done
