### ISSUE TITLE
design changes 

### ISSUE THREAD

**Issue by Basler182** [machbarschaft/machbarschaft-android#32]
- [x] more contrast in the landing page (orange font color gets lost on orange background)

- [x]  change the yellow color in the map view 

- [x]  add contours to the flags, so that they don't melt into each other in the map view

- [x] change font color in step 2 (black font color is hard to read on blue background)

- [x] try to play a little more around with different font sizes, to make clear which elements are in focus also try to make less important parts greyer to optimize the importance of different elements visually. stuff that is in focus should be bigger and blacker

- [x] style the medical warnings page (and change the text to the new shorter version)

**Comment by moonlight200** [comment]
Are we still missing anything here?

**Comment by Basler182** [comment]
> Are we still missing anything here?

We still have some minor design changes left, but we rather open a new issue for them. Those from above are all completed.
