### ISSUE TITLE
Save login details

### ISSUE THREAD

**Issue by moonlight200** [machbarschaft/machbarschaft-android#5]
When the user is logging in, the new state (= logged in) is not saved. Thus, the next time the app is opened, the user has to enter their phone number again.
Save the login details. Also make sure that there is only one place where these details are stored and accessed. I think we currently have at least two places, once in the `LoginActivity` and once in the database when the account is loaded.

**Comment by Basler182** [comment]
Where do we prefer to save this status? I personally would suggest saving it in the shared preferences. So we have all the information locally and in case of no internet connection, the user would be still able to fully view his current order and go through his steps without any restrictions.

**Comment by jtshark** [comment]
Firebase can save the login data and other information like the order itself, (also offline). 
We can simply use the Firebase functions ;)
I think that's much easier.

**Comment by moonlight200** [comment]
But we still have to save some kind of Firebase ID or auth token to access that data.

**Comment by jtshark** [comment]
yes i can do it right away.
But I saw that we are using with SharedPreferences for saving. Do we want to continue using SharedPreferences or use the storage functions of Firebase for saving the data on the phone?

**Comment by Basler182** [comment]
I didn't know anything about the firebase offline storage, but I am totally fine if you want to implement it. Just go for it :)

**Comment by jtshark** [comment]
#19
