### ISSUE TITLE
Adapt to JvM Design 

### ISSUE THREAD

**Issue by Basler182** [machbarschaft/machbarschaft-android#7]
Adapt our design to the suggestions from JvM.

**Comment by moonlight200** [comment]
- [ ] Update OrderDetailActivity
- [x] Update OrderAcceptActivity
- [ ] Update OrderCarryOutActivity
- [ ] Update OrderEnRouteActivity
- [ ] Update OrderDoneActivity

**Comment by JulianWieners** [comment]
All existing pages updated - done
